modLoader = "javafml"
loaderVersion = "[47,)"
license = "GNU-AGPL-v3.0"
issueTrackerURL = "https://github.com/Salandora/RideablePolarBears/issues"

[[mods]]
modId = "rideablepolarbears"
version = "${version}"
displayName = "RideablePolarBears"
logoFile = "assets/rideablepolarbears/icon.png"
displayURL = "https://github.com/Salandora/RideablePolarBears"
authors = "Salandora"
description = '''Enables you to breed and ride polar bears'''

[[dependencies.rideablepolarbears]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.rideablepolarbears]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,1.20.2)"
ordering = "NONE"
side = "BOTH"