modLoader = "javafml"
loaderVersion = "[4,)"
license = "GNU-AGPL-v3.0"
issueTrackerURL = "https://github.com/Salandora/RideablePolarBears/issues"

[[mods]]
modId = "rideablepolarbears"
version = "${version}"
displayName = "RideablePolarBears"
logoFile = "assets/rideablepolarbears/icon.png"
displayURL = "https://github.com/Salandora/RideablePolarBears"
authors = "Salandora"
description = '''Enables you to breed and ride polar bears'''

[[dependencies.rideablepolarbears]]
modId = "neoforge"
type = "required"
versionRange = "[21.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.rideablepolarbears]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.4,)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "rideablepolarbears.common.mixins.json"