apply plugin: libs.plugins.shadow.get().getPluginId()
apply plugin: libs.plugins.minotaur.get().getPluginId()
apply plugin: libs.plugins.cursegradle.get().getPluginId()

architectury {
    injectInjectables = false
    platformSetupLoomIde()
    forge()
}

loom {
    runtimeOnlyLog4j = true

    if (project(":common").loom.accessWidenerPath.getOrNull() != null && project(":common").loom.accessWidenerPath.asFile.get().exists()) {
        accessWidenerPath.set(project(":common").loom.accessWidenerPath)
    }

    forge {
        convertAccessWideners = true
        if (accessWidenerPath.getOrNull() != null && accessWidenerPath.asFile.get().exists()) {
            extraAccessWideners.add loom.accessWidenerPath.get().asFile.name
        }

        mixinConfig "${mod_id}.common.mixins.json"
        // mixinConfig "${mod_id}.mixins.json"
    }
}

configurations {
    common {
        canBeResolved = true
        canBeConsumed = false
    }
    compileClasspath.extendsFrom common
    runtimeClasspath.extendsFrom common
    developmentForge.extendsFrom common

    // Files in this configuration will be bundled into your mod using the Shadow plugin.
    // Don't use the `shadow` configuration from the plugin itself as it's meant for excluding files.
    shadowBundle {
        canBeResolved = true
        canBeConsumed = false
    }
}

repositories {
    maven {
        name = 'NeoForged'
        url = 'https://maven.neoforged.net/releases/'
    }
}

dependencies {
    forge libs.neoforge

    common(project(path: ":common", configuration: "namedElements")) { transitive false }
    shadowBundle(project(path: ":common", configuration: "transformProductionForge"))
}

processResources {
    inputs.property 'version', project.version

    filesMatching('META-INF/mods.toml') {
        expand version: inputs.properties.version
    }
}

shadowJar {
    configurations = [project.configurations.shadowBundle]
    archiveClassifier = 'dev-shadow'
}

remapJar {
    inputFile.set shadowJar.archiveFile
}

publishing {
    publications {
        mavenFabric(MavenPublication) {
            artifactId = base.archivesName.get()
            version = project.version
            artifact(remapJar) {
                builtBy remapJar
                classifier ''
            }
        }
    }

    // See https://docs.gradle.org/current/userguide/publishing_maven.html for information on how to set up publishing.
    repositories {
        // Add repositories to publish to here.
    }
}

modrinth {
    debugMode = providers.environmentVariable("MODRINTH_TOKEN").getOrNull() == null

    token = providers.environmentVariable("MODRINTH_TOKEN").getOrElse("")

    projectId = 'rideablepolarbears'
    versionNumber = version
    versionName = "${mod_name}-${version}"
    versionType = 'release'
    file = remapJar.archiveFile
    changelog = rootProject.file('CHANGELOG.md').text
    gameVersions = [libs.versions.minecraft.get()]
    loaders = ['neoforge']
    detectLoaders = false

    /*dependencies {
        // A special DSL for creating dependencies
        // scope.type
        // The scope can be `required`, `optional`, `incompatible`, or `embedded`
        // The type can either be `project` or `version`
    }*/
}

curseforge {
    curseGradleOptions.debug = providers.environmentVariable("CURSEFORGE_TOKEN").getOrNull() == null

    apiKey = providers.environmentVariable("CURSEFORGE_TOKEN").getOrElse("invalid")

    curseGradleOptions.javaIntegration = false
    curseGradleOptions.forgeGradleIntegration = false
    curseGradleOptions.javaVersionAutoDetect = false

    //noinspection GroovyAssignabilityCheck
    project {
        id = '932424'
        releaseType = 'release'
        changelogType = 'markdown'
        changelog = rootProject.file('CHANGELOG.md')

        addGameVersion libs.versions.minecraft.get()
        addGameVersion 'NeoForge'

        mainArtifact(remapJar) {
            displayName = "${mod_name}-${version}"
        }

        /*relations {
        }*/
    }
}